services:
  - type: web
    name: tech-store
    runtime: docker
    region: singapore
    plan: starter
    dockerfile: Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: techstore-db
          property: connectionString
    healthCheckPath: /
    healthCheckInterval: 30

databases:
  - name: techstore-db
    engine: postgres
